export const ROUTES = {
  login: "/",
  dashboard: "/dashboard/stats",
  profile: "/dashboard/profile",
  users: "/dashboard/users",
  userDetailsPage: (id: number | string) => `/dashboard/user-details/${id}`,
  properties: "/dashboard/properties",
  bookings: "/dashboard/bookings",
  approvals: "/dashboard/approvals",
  approvalDetails: "/dashboard/approvals/:id",
  buildApprovalDetails: (id: number) => `/dashboard/approvals/${id}`,
  reviews: "/dashboard/reviews",
  propertyReviews: "/dashboard/propertyReviews",
  cancellations: "/dashboard/cancellations",
  guestReviews: "/dashboard/guestReviews",
  governmentId: "/dashboard/government-id",
  cancelRequests: "/dashboard/cancel-requests",
  notifications: "/dashboard/notifications",
  cancellationPolicy: "/dashboard/cancellationPolicy",
  privacyPolicy: "/dashboard/privacyPolicy",
  termsAndConditions: "/dashboard/termsAndConditions",
  platformCommission: "/dashboard/platformCommission",
  payments: "/dashboard/payments",
  payout: "/dashboard/payouts",
  financialReport: "/dashboard/financial-report",
  blogs: "/dashboard/blogs",
  blogDetails: "/dashboard/blogs/:slug",
  buildBlogDetails: (slug: string) => `/dashboard/blogs/${slug}`,
  articles: "/dashboard/articles",
  articleDetails: "/dashboard/articles/:slug",
  buildArticleDetails: (slug: string) => `/dashboard/articles/${slug}`,
  notFound: "*",
};
